### ISSUE TITLE
script error if data in the exp_rate column

### ISSUE THREAD

**Issue by An0rakX** [automorphis/Cogstruction#3]
I imported the cogs_data and empties_datas using AfkKun's IdleonCogExporter, when running the script it gave this error:

```
:\Users\Jonathan\AppData\Roaming\IdleonSaver\cogstruction\Cogstruction>python main.py
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\IdleonSaver\cogstruction\Cogstruction\main.py", line 63, in <module>
    cog_datas = read_cog_datas(cog_datas_filename)
  File "C:\Users\Jonathan\AppData\Roaming\IdleonSaver\cogstruction\Cogstruction\file_readers.py", line 43, in read_cog_datas
    _check_for_Cog_Data_File_Error("exp_rate", "int", row, i, filename)
  File "C:\Users\Jonathan\AppData\Roaming\IdleonSaver\cogstruction\Cogstruction\file_readers.py", line 106, in _check_for_Cog_Data_File_Error
    raise Cog_Data_File_Error(row_num, key, filename, should_be)
file_readers.Cog_Data_File_Error: Error in `cog_datas.csv` on row 12, column `exp_rate`. Entry should be a positive integer or zero.
```
I tried editing row 12 exp_rate to either 0 or 1 which did not work
![image](https://user-images.githubusercontent.com/88849471/144076518-f2d542f2-36c2-4894-918b-aad6df78ec73.png)

After deleting all the values in the exp_rate column the script ran successfully.

Guessing there is an issue with the script reading data in that column, maybe due to update. No idea.
Not sure of the effect of delete the data from this column but maybe this will be helpful to anyone else trying this.

Kind regards and thanks for you hard work :)

**Comment by isaackhlam** [comment]
Hi I don't whether you are still playing this game and using this tool, you may try to set all `exp_rate` of your cog to positive Int/zero
