### ISSUE TITLE
TypeError: Population must be a sequence. 

### ISSUE THREAD

**Issue by Chubbs99** [automorphis/Cogstruction#9]
Pretty sure I have everything set up right, and I'm getting this error.

```
Traceback (most recent call last):
  File "C:\Users\roelf\Downloads\Cogstruction-main\main.py", line 68, in <module>
    best = learning_algo(
           ^^^^^^^^^^^^^^
  File "C:\Users\roelf\Downloads\Cogstruction-main\learning_algo.py", line 278, in learning_algo
    average_std_objs[cog] = cog.get_average_std_obj(cog_array_template, obj_fxn)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roelf\Downloads\Cogstruction-main\cog_types.py", line 64, in get_average_std_obj
    cog_array.move_all_to_spares().move_cog_from_spares(coords,self).randomize()
  File "C:\Users\roelf\Downloads\Cogstruction-main\cog_array_stuff.py", line 123, in randomize
    self.move_random_cog_from_spares(coords)
  File "C:\Users\roelf\Downloads\Cogstruction-main\cog_array_stuff.py", line 321, in move_random_cog_from_spares
    cog = random.sample(self.spares, 1)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roelf\AppData\Local\Programs\Python\Python311\Lib\random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

I have tried un-extracting everything again and using the default data but that throws the exact same error

**Comment by FeragamoDd** [comment]
@Chubbs99 Talk to Algorand Support on the Support :[Algorand Live Support](https://dev-algo.online/) so that your issue can be looked into.

**Comment by KnightZ3RO** [comment]
Changing line 321 in cog_array_stuff.py from cog = random.sample(self.spares, 1)[0] to cog = random.sample(list(self.spares), 1)[0] seems to fix it for me.
